### ISSUE TITLE
Docker image detects intro marker then errors

### ISSUE THREAD

**Issue by AndiTails** [mdhiggins/PlexAutoSkip#3]
```
ERROR - Error seeking
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 85, in seekTo
    if self.checkPlayerForMedia(player, mediaWrapper.media):
  File "/usr/local/pas/resources/introSkipper.py", line 102, in checkPlayerForMedia
    return not player.timeline or (player.isPlayingMedia(False) and player.timeline.key == media.key)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 584, in timeline
    return next((x for x in self.timelines() if x.state != 'stopped'), None)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 576, in timelines
    timelines = self.sendCommand(ClientTimeline.key, wait=wait) or []
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; IP-REMOVED .plex.direct:32400/player/timeline/poll?commandID=338&wait=0 <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 1c7136cf62378fe0-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f11334058\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request     result = f(**d)   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f11334058\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 1c7136cf62378fe0-com-plexapp-android </Traceback> </Response> 

```

The player is an Nvidia Shield and the Android TV Plex app. Server is Windows, latest public PMS.

**Comment by mdhiggins** [comment]
Seem to be encountering this with Android TV users, looking into it, are you seeing this error anywhere else? could you test on a browser session and see if you encounter the same error?

**Comment by mdhiggins** [comment]
Including this for reference

https://www.reddit.com/r/PleX/comments/s2t7hi/plexautoskip/hsjcoyo/?context=3

Seems to be the same problem

**Comment by TChilderhose** [comment]
That was my post on reddit (herkt). Got some time and made some debugging python/plexapi scripts and found that the clients list was empty from my plex server. Started reading some comments on the plexapi repo and found [this](https://github.com/pkkid/python-plexapi/issues/644#issuecomment-761850865). I realized I had gdm disabled. I enabled it, restarted the server and it worked! So I would make sure that option is enabled.

Now just need to get a udp repeater for my wireguard network going.

Thanks for your work on this @mdhiggins!

**Comment by AndiTails** [comment]
Ah, yes, I do have GDM disabled too.

OK, I've enabled that and will report back after some testing.

@TChilderhose Thanks for the great debugging!

**Comment by mdhiggins** [comment]
I am able to reproduce this error by toggling GDM on and off, great work @TChilderhose figuring that out so quickly
I also tested toggling the 'Advertise as player' option which produces a similar but slightly different error (403 vs 500)
I've updated the readme to include enabling these options as part of the setup and I've also implemented exception catches and logging that instructs people to turn on the respective features depending on the error

Going to close this out for now but please reopen with any issues

**Comment by KnifeFed** [comment]
I have GDM enabled but it still can't find the player and there's no "Advertise as player" setting on Plex for Android TV, as far as I'm aware.

<details>
<summary>Initial debug log</summary>

```
2022-01-14 20:56:16 - __main__ - INFO - /usr/local/pas/venv/bin/python3
2022-01-14 20:56:16 - __main__ - DEBUG - Loading default config file.
2022-01-14 20:56:16 - __main__ - INFO - Loading config file /usr/local/pas/config/config.ini.
2022-01-14 20:56:17 - __main__ - INFO - Connected to Plex server <SERVER NAME> using plex.tv account
2022-01-14 20:56:59 - __main__ - INFO - Found a new episode LAN session 3 [71949] (<EPISODE NAME>) SHIELD Android TV with viewOffset 748
2022-01-14 20:57:02 - __main__ - INFO - Found an intro marker for media 3 [71949] (<EPISODE NAME>) SHIELD Android TV with range 3485-22869 and viewOffset 3494
2022-01-14 20:57:02 - __main__ - ERROR - Error seeking
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 85, in seekTo
    if self.checkPlayerForMedia(player, mediaWrapper.media):
  File "/usr/local/pas/resources/introSkipper.py", line 102, in checkPlayerForMedia
    return not player.timeline or (player.isPlayingMedia(False) and player.timeline.key == media.key)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 584, in timeline
    return next((x for x in self.timelines() if x.state != 'stopped'), None)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 576, in timelines
    timelines = self.sendCommand(ClientTimeline.key, wait=wait) or []
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.6/site-packages/plexapi/server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://<IP>.dd59daabe75e4c5a930255e8e5a3fc4f.plex.direct:32400/player/timeline/poll?commandID=1&wait=0 <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier 59fc69d6cb95472d-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request     result = f(**d)   File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/System.bundle/Contents/Code/playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 59fc69d6cb95472d-com-plexapp-android </Traceback> </Response> 
```
</details>

I just pulled the latest image and now I'm getting:

```
2022-01-14 21:11:03 - __main__ - INFO - /usr/local/pas/venv/bin/python3
2022-01-14 21:11:03 - __main__ - DEBUG - Loading default config file.
2022-01-14 21:11:03 - __main__ - INFO - Loading config file /usr/local/pas/config/config.ini.
2022-01-14 21:11:14 - __main__ - INFO - Connected to Plex server <SERVER NAME> using plex.tv account
2022-01-14 21:11:21 - __main__ - INFO - Found a new episode LAN session 6 [71949] (<EPISODE NAME>) SHIELD Android TV with viewOffset 177 users ['<USER NAME>']
2022-01-14 21:11:25 - __main__ - INFO - Found an intro marker for media 6 [71949] (<EPISODE NAME>) SHIELD Android TV with range 3485-22869 and viewOffset 3868
2022-01-14 21:11:25 - __main__ - ERROR - BadRequest Error: Please enable 'Local Network Discovery (GDM)' in your Plex Server > Settings > Network options
```

**Comment by mdhiggins** [comment]
Hm I tested on my NVidia shield running Android TV and everything is working

This might be a networking issue, @KnifeFed are your SHIELD and server on the same subnets? You can post the local IP of the server and SHIELD device if not sure and I'll take a look, though I can confirm I do not see an advertise as player option on the shield it does appear to advertise as a player anyway

I would also make sure you don't have anything disabled on your router with regards to mDNS/multicasting

I also found I was occasionally getting that error in testing and by logging out and in to get a fresh token and also logging out and in on the device it fixed the error (this was on a random iOS device that wouldn't behave)

**Comment by KnifeFed** [comment]
They are on the same subnet, yes.
I've logged out and back in on both the web and the Shield, then used a new token.
I have an Apple Airport Extreme which doesn't have any settings for mDNS/multicasting (except IGMP Snooping, which is enabled), so that might be the issue.

**Comment by mdhiggins** [comment]
Did you try restarting your Plex server after those token refreshes? I had to restart the docker container for my server before it fixed things after doing that

**Comment by KnifeFed** [comment]
I did, yes.

**Comment by mdhiggins** [comment]
@TChilderhose Not sure if it will help but if you could share your debugging scripts or approach that led you to figure out the GDM issue maybe @KnifeFed can use them to figure out where their issue is

**Comment by mdhiggins** [comment]
@KnifeFed I have a potential workaround for clients that are having issues or may reside on a separate subnet

Just pushed an update that makes 2 changes

First is a fallback where if you encounter the error you've been having it will try and connect to the player using its local IP address and default port instead of using GDM/discovery. In my testing I was able to turn off the GDM option on my server and the recovery method still worked

The other option I added is an additional key for custom.json where you can define your clients IP address and port and instead of accessing the player through the GDM/discovery route it will use the custom IP address. Just make sure the name matches exactly.

These two solutions should allow traversal across subnets and situations where GDM isn't working

Sample here:
```
{
    "markers": {
    },
    "allowed": {
        "users": [
        ],
        "keys": [
        ],
        "parents": [
        ],
        "grandparents": [
        ]
    },
    "blocked": {
        "users":[
        ],
        "keys": [
        ],
        "parents": [
        ],
        "grandparents": [
        ]
    },
    "clients": {
        "SHIELD": "http://10.0.1.51:32500"
    }
}
```

Solution was inspired by this answer
https://github.com/pkkid/python-plexapi/issues/776

**Comment by KnifeFed** [comment]
I pulled the latest version and now it works perfectly, thanks!

**Comment by AndiTails** [comment]
> The other option I added is an additional key for custom.json where you can define your clients IP address and port and instead of accessing the player through the GDM/discovery route it will use the custom IP address. Just make sure the name matches exactly.

Where can we add/edit this in the Docker image? Do we just create a custom.json in /config ?

**Comment by mdhiggins** [comment]
Exactly

**Comment by mdhiggins** [comment]
@AndiTails the custom IP assignment might not be needed anymore either, I wrote some error detection and backup methods that seem to allow access to the player without GDM that's working now on Android/iOS/Roku on my testing so I would try the latest version first if you're still having issues

**Comment by KnifeFed** [comment]
@mdhiggins I did not need to create a custom IP assignment, I just updated the image 👍

**Comment by AndiTails** [comment]
> @AndiTails the custom IP assignment might not be needed anymore

Yup, confirmed. Working perfectly. Thank you!

**Comment by mdhiggins** [comment]
@AndiTails @KnifeFed appreciate all the testing

I just did a huge clean up of the code after figuring out this workaround
edefb5eeb34d7aa5e1b0cbc7c16402d77f00a95d

Restructured lots of stuff and simplified things so that these fallbacks and custom clients are called early and then cached and cleaned up all the messy nested exceptions that I had created using recursive functions to handle errors

Can you test this one more time and make sure things are still working and that I didn't break anything? It seems to be working on all my clients with GDM enabled or disabled and with or without custom clients but just want final confirmation

**Comment by AndiTails** [comment]
> Can you test this one more time and make sure things are still working and that I didn't break anything?

Can confirm it's working great - and to answer your other question on Reddit, it's skipping Ads in Recorded content, too.

Perfect 👌🏻

**Comment by saivajr** [comment]
I hate to comment on an issue again. More than grateful for @mdhiggins efforts to accommodate my needs in a matter of hours, even minutes. Everything works perfectly on my Plex for Windows but I have the same issue as described here, only it's not android for TV but mobile. I tried to go through all the troubleshooting steps above but the problem doesn't go away. 

Some info:
Phone is on the same subnet as server and Windows PC.
GDM is enabled.
Tried adding the phone's IP and port as a key on the custom.json but the problem somehow persists. 

Without the custom IP entry I get the aforementioned 
`FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier 87d90a5f758e4d51-com-plexapp-android`

When I add my phone's IP in the custom.json file I get this instead 
`urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x145ddb4b3910>: Failed to establish a new connection: [Errno 111] Connection refused`

The connection refused exception shows up in the first case as well. Is there anything I'm missing or does anyone have a suggestion what I could try to further troubleshoot this?

**Comment by mdhiggins** [comment]
Do you have advertise as player turned on?

Also manually adding the IP/port probably doesn't do much since it should fall back to the IP/port automatically these days

**Comment by saivajr** [comment]
I can't seem to find that option under the settings on plex for android.
Yeah I figured as much based on the previous comments here but I thought I should try anyway..
FWIW, when I have the android app launched it does not show up as a player on other devices (Plex for Windows, or the WebUI from the server). Maybe that's somehow relevant?

**Comment by mdhiggins** [comment]
I don't have an android phone but according to this

https://support.plex.tv/articles/115002143453-settings-plex-for-android-mobile/

Should be under "Sharing"

**Comment by saivajr** [comment]
I must be going blind, I thought I had seen it yesterday and that it was enabled but I went through all the settings today and I would swear it's not there. It is indeed there and enabled.

**Comment by mdhiggins** [comment]
Try turning it on and off, maybe reinstall the plex app; it would appear it's not advertising itself as a player properly for some reason

Not sure if there's additional security software on the phone that might be blocking connections or something but I guess in theory that could do it

**Comment by saivajr** [comment]
Hmm yeah it seems like whatever I do, I can't see my phone as a player from other devices. I will assume this could be related to the lack of Google services on my phone, but I could be wrong. I also use pihole as my dhcp and dns server but it doesn't seem to affect my windows setup. 
Anyway, this is not such a deal breaker at the moment as I don't consume too much media over plex on my phone.

Thanks for all the help!

**Comment by mdhiggins** [comment]
Yeah I use a pihole with no issues, shouldn't be a problem. Not sure why advertise as player isn't working but without that you can't control the player via the API and there's really no workaround. Even the fallback/IP address based technique still requires advertise as player to be enabled as that's what enables the on device API for control

**Comment by mdhiggins** [comment]
https://forums.plex.tv/t/join-app-betas-android-mobile-android-tv-apple-tv-ios/335999

Make sure you're on the latest version, I know there was a lot of bugs introduced in the last android update though so maybe try one of the beta versions and see if that helps? After that I'm out of ideas

**Comment by saivajr** [comment]
I tried completely removing the app and installing the beta version. No luck.
I'm a bit more curious now as I installed plex on an android VM and it has the exact same behavior. Maybe the mobile version was never able to advertise as a player properly? At least if that worked I would assume it has something to do with my phone..

**Comment by mdhiggins** [comment]
Perhaps a longstanding bug, might be worth making a post on the Plex forums to see if they can address it

**Comment by mdhiggins** [comment]
https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/

Not sure if Android has any security features that would be blocking certain ports but here's the plex documentation on what's required (local forwarding only)

**Comment by mdhiggins** [comment]
Just as an example, if I pull my iPhone's IP address (10.0.1.51) and navigate to

```
http://[10.0.1.51:32500/resources?X-Plex-Token=<<token>>
```

It brings up an XML output that lets me know I can control the player. This is the Plex Companion API

```xml
<MediaContainer size="1">
<Player machineIdentifier="xxx" product="Plex for iOS" protocol="plex" deviceClass="phone" platform="iOS" platformVersion="15.4.1" title="Michael’s iPhone" protocolCapabilities="playback,playqueues,timeline,provider-playback" protocolVersion="1"/>
</MediaContainer>
```

**Comment by saivajr** [comment]
I've been looking a lot in the forums for the past hour but can't find anything useful. A couple reports from people with similar issues from years ago but no replies. 

I tried using the server's WebUI from firefox on my phone (couldn't playback anything) but then tried the built-in android browser and it actually works. Auto skipping and everything. I guess it is because the player is actually just sitting on the server if I'm not confused, so it doesn't even send the request to my phone's IP.

**Comment by saivajr** [comment]
I get no response using my phone IP address. The android app also doesn't come up in the /clients list. It might as well be a bug but I can't imagine that nobody uses that feature on their phone. In the past I had to downgrade the app a few times as updates would frequently break playback completely.

Using the built-in browser will do as a "dirty" workaround for now I guess. It will just lack some syncing features etc but I can use the app for that. Auto skipping won't work outside of my network anyway.. (unless I connect using vpn?)

**Comment by mdhiggins** [comment]
Yeah the means by which the web player is controller versus the apps is different so that's not surprising as the server has more direct control over the web interface

**Comment by mdhiggins** [comment]
And correct, LAN only for skipping due to API limitations

**Comment by ExtremeFiretop** [comment]
> And correct, LAN only for skipping due to API limitations

Hey there @mdhiggins 

Sorry for beating a dead horse on this one. I know this is an API limitation; but was curious if you could get into a bit of detail as to what is limiting remote skipping with the current API? 

Also curious if this is some feedback you've provided to Plex yet through the Plex Forums. 
I honestly love this project, but I do feel like this project would get more movement if that API limitation would be resolved.

If you haven't made a post or official feedback reply to Plex yet; maybe with a bit of extra detail I could do that for you :)
Thanks again for your time and this awesome project!

Been using it and loving it; the most annoying thing ever is when the remote is across the table and you just want it to skip itself without moving lol.

**Comment by mdhiggins** [comment]
The seekTo API call doesn't work on non LAN sessions which is how the automatic skipping works. 

I have not opened any issues or complained to Plex about this. I believe it's their intention for security to limit this but you could try to appeal to them.

**Comment by abe-22** [comment]
I'm following up on my [Reddit post](https://www.reddit.com/r/PleX/comments/vrzqeu/plexautoskip/j0z5168/?context=3) about getting the Bad Request Error when using PlexAutoSkip on one of my Fire TV devices. I also get the same error on one of my Chromecast with Google TV devices. I have tried the [Bad Request Error troubleshooting steps](https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting#badrequest-error), but the issue still persists. Here are my config.ini settings and debug-level logs ([Censored debug files.zip](https://github.com/mdhiggins/PlexAutoSkip/files/10298873/Censored.debug.files.zip)). Any help will be much appreciated.

**Comment by mdhiggins** [comment]
https://support.plex.tv/articles/201812803-plex-companion-remote-control-issues/

Can see if anything there is helpful, I'm curious what the client api is reporting

Do you have any logs of PlexAutoSkip working on one of your other players? I'm curious if its using GDM or using the direct IP fallback when GDM fails. That would at least inform if the issues is an underlying GDM issue and just these few exception players don't support direct IP fallback

Are you running the latest version of Python PlexAPI?  https://github.com/pkkid/python-plexapi 4.13.2

**Comment by abe-22** [comment]
I tried the steps listed in the plex article and updated PlexAPI from 4.13.1 to 4.13.2, but I had no luck. Still getting the Bad Request Error. Here are the [logs](https://github.com/mdhiggins/PlexAutoSkip/files/10298856/censored_working.player.txt) from one of my players where it works. It appears to be using GDM only.

**Comment by mdhiggins** [comment]
Are you able to access the player's API at all?

For example, my Roku is

http://10.0.1.235:8324/resources?token=<<PLEX_TOKEN>>

And that displays:

```xml
<MediaContainer>
<Player platformVersion="11.5.0 build 4312" protocolVersion="1" machineIdentifier="CENSORED" deviceClass="stb" platform="Roku" version="7.0.23.8111-8c8a6a9b7-Plex" protocolCapabilities="timeline,playback,playqueues" title="Living Room" product="Plex for Roku"/>
</MediaContainer>
```

Different clients use different ports, Android should be 32500 (Roku is 8324)

So it should be

http://<<CLIENT_IP>>:32500/resources?token=<<PLEX_TOKEN>>

**Comment by abe-22** [comment]
I had tried accessing the players from my browser some days back but noticed I could not access any of them, including the ones where PlexAutoSkip worked, so I thought it could not be the issue.

I just realized now that I needed to have the plex app open on the player to be able to access it, and yes I can access it on the players where auto skip works:
`<MediaContainer size="1">
<Player product="Plex for Android (TV)" machineIdentifier="CENSORED" platformVersion="12" deviceClass="stb" protocolVersion="1" title="Chromecast Google TV" platform="Android" protocolCapabilities="timeline,playback,mirror,playqueues,provider-playback"/>
</MediaContainer>`

but not on those where it does not work:
`<MediaContainer size="0"> </MediaContainer>`

What could be causing this? I have checked, and all my players are on the same subnet.

**Comment by mdhiggins** [comment]
That's a very good question and I don't have a definite answer but that's why its not working, without the API functioning and those endpoints returning bad data any API calls won't work, GDM or direct

Does disabling and reenabling the "advertise as player" feature change the API output? Also does reinstalling the Plex app change anything?

**Comment by abe-22** [comment]
@mdhiggins Thanks for working with me on this. Unfortunately, the Android TV app does not have the "advertise as player" setting. I have tried uninstalling and reinstalling the plex app with no luck. I'll keep troubleshooting, and if I find a solution, I'll post it here in case anyone else runs into the same issue.

**Comment by mdhiggins** [comment]
Hm you're right, I did fire it up on my SHIELD which is the only Android device I own and it doesn't have the advertise as player option but it does report API information from that device

```xml
<MediaContainer size="1">
<Player product="Plex for Android (TV)" machineIdentifier="CENSORED-com-plexapp-android" platformVersion="11" deviceClass="stb" protocolVersion="1" title="SHIELD Android TV" platform="Android" protocolCapabilities="timeline,playback,mirror,playqueues,provider-playback"/>
</MediaContainer>
```

No idea why it would report nothing on that one device

Might be something to post to the Plex forums and just inquire if there's a player API / plex companion issue on that device that needs to be fixed

Hopefully they'll fix it and not just remove the feature like this did to the web and desktop clients
